ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "partnerUserId" TEXT;
ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "partnerAccepted" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Post" ADD CONSTRAINT "Post_partnerUserId_fkey" FOREIGN KEY ("partnerUserId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
