ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "contact" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "defaultFollowDuration" TEXT DEFAULT 'forever';
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "relationshipStatus" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "partnerName" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "partnerId" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "city" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "district" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "autoReply" TEXT;
