import type { IconName } from './paths'

/**
 * Ponte de migração: nome do Ionicons → ícone da Luxee.
 * Serve para trocar `<Ionicons name="chevron-back" …/>` por `<Icon name={ION.['chevron-back']} …/>`
 * sem ter de decidir caso a caso. As variantes `-outline` e sólidas apontam para o
 * mesmo desenho — o preenchimento passa a ser a prop `fill`, não um ícone diferente.
 */
export const ION: Record<string, IconName> = {
  add: 'plus',
  'add-circle': 'plus',
  'alert-circle': 'alert-circle',
  'arrow-forward': 'arrow-right',
  'arrow-back': 'arrow-left',
  'arrow-up': 'arrow-up',
  'arrow-down': 'arrow-down',
  'arrow-undo-outline': 'reply',
  'ban-outline': 'ban',
  'calendar-outline': 'calendar',
  'call-outline': 'phone',
  camera: 'camera',
  'camera-outline': 'camera',
  'chatbubble-outline': 'message',
  'chatbubble-ellipses-outline': 'message',
  chatbubbles: 'message',
  checkmark: 'check',
  'checkmark-done': 'check-double',
  'chevron-back': 'chevron-left',
  'chevron-forward': 'chevron-right',
  'chevron-up': 'chevron-up',
  'chevron-down': 'chevron-down',
  close: 'close',
  'close-outline': 'close',
  'close-circle': 'close',
  'close-circle-outline': 'close',
  contrast: 'contrast',
  'contrast-outline': 'contrast',
  'create-outline': 'edit',
  'diamond-outline': 'diamond',
  'document-text-outline': 'file-text',
  'download-outline': 'download',
  earth: 'globe',
  'ellipsis-horizontal': 'more-horizontal',
  'ellipsis-vertical': 'more-vertical',
  'exit-outline': 'logout',
  'eye-outline': 'eye',
  'flag-outline': 'flag',
  'folder-outline': 'folder',
  'globe-outline': 'globe',
  'grid-outline': 'grid',
  'happy-outline': 'smile',
  heart: 'heart',
  'heart-outline': 'heart',
  'heart-circle': 'heart',
  'home-outline': 'home',
  'hourglass-outline': 'hourglass',
  'image-outline': 'image',
  images: 'images',
  'images-outline': 'images',
  information: 'info',
  'information-circle-outline': 'info',
  'location-outline': 'location',
  'lock-closed': 'lock',
  'log-out-outline': 'logout',
  'megaphone-outline': 'megaphone',
  mic: 'mic',
  'moon-outline': 'moon',
  notifications: 'bell',
  'notifications-outline': 'bell',
  people: 'users',
  'people-outline': 'users',
  'pencil-outline': 'edit',
  person: 'user',
  'person-add': 'user-plus',
  'person-add-outline': 'user-plus',
  'phone-portrait-outline': 'smartphone',
  play: 'play',
  'play-circle': 'play',
  'qr-code-outline': 'qr-code',
  refresh: 'refresh',
  'refresh-outline': 'refresh',
  'return-down-forward': 'reply',
  'ribbon-outline': 'award',
  'scan-outline': 'scan',
  search: 'search',
  'search-outline': 'search',
  send: 'send',
  'settings-outline': 'settings',
  'share-outline': 'share',
  'shield-checkmark-outline': 'shield-check',
  'sunny-outline': 'sun',
  'swap-horizontal': 'swap',
  'time-outline': 'clock',
  'trash-outline': 'trash',
  'videocam-outline': 'video',
  'wifi-outline': 'wifi',
}
